title: Tuomas Mäenpää
#logo: /assets/img/headshot_circle.pnh
description: Data analyst and software designer
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
